/// 운동 이름 사전. UI 문구(arb)와 떼어 둔 이유는 성격이 다르기 때문이다 —
/// 이건 **번역문이 아니라 데이터**다. 한 운동이 언어마다 다른 이름을 갖되
/// 같은 한 줄에 머물러야, "영어로 치고 한글로 보는" 게 가능해진다.
///
/// 표시 이름은 기기 언어를 따르고, **검색은 여덟 언어를 전부 받는다.**
/// 한국인 트레이너가 'bench' 로 찾든 외국인 회원이 '벤치' 로 찾든 같은
/// 운동에 닿는다. 초성(ㅂㅊㅍㄹㅅ)도 검색 키다.
///
/// 마스터 테이블이 아니다. 실제 어휘는 사용자가 친 이름에서 자란다.
library;

class Exercise {
  const Exercise(
    this.ko,
    this.en,
    this.ja,
    this.zhHans,
    this.zhHant,
    this.es,
    this.vi,
    this.th, [
    this.alias = '',
    this.more = const [],
  ]);

  final String ko, en, ja, zhHans, zhHant, es, vi, th;

  /// 어느 이름에도 안 들어가는 약어·별칭. 'rdl', 'ohp', '턱걸이' 같은 것.
  final String alias;

  /// 기구 제품명 같은 별칭 여럿 — '해머 하이로우', 'Hammer Strength Iso-Lateral High Row'.
  /// 사람이 헬스장 기구 이름으로 쳐도 같은 운동이다.
  final List<String> more;

  String name(String lang) => switch (lang) {
    'en' => en,
    'ja' => ja,
    'zh_Hans' => zhHans,
    'zh_Hant' => zhHant,
    'es' => es,
    'vi' => vi,
    'th' => th,
    _ => ko,
  };

  /// 검색이 훑는 전부.
  List<String> get keys => [
    ko,
    en,
    ja,
    zhHans,
    zhHant,
    es,
    vi,
    th,
    alias,
    ...more,
    chosungOf(ko),
  ].where((s) => s.isNotEmpty).map((s) => s.toLowerCase()).toList();
}

/// 기기 로케일 → 이 사전의 언어 키. 중국어만 문자 체계를 갈라 본다.
String langKeyOf(String languageCode, String? scriptCode, String? countryCode) {
  if (languageCode != 'zh') return languageCode;
  final hant =
      scriptCode == 'Hant' ||
      const ['TW', 'HK', 'MO'].contains(countryCode ?? '');
  return hant ? 'zh_Hant' : 'zh_Hans';
}

const _cho = [
  'ㄱ',
  'ㄲ',
  'ㄴ',
  'ㄷ',
  'ㄸ',
  'ㄹ',
  'ㅁ',
  'ㅂ',
  'ㅃ',
  'ㅅ',
  'ㅆ',
  'ㅇ',
  'ㅈ',
  'ㅉ',
  'ㅊ',
  'ㅋ',
  'ㅌ',
  'ㅍ',
  'ㅎ',
];

/// "벤치프레스" → "ㅂㅊㅍㄹㅅ". 한글이 아닌 글자는 그대로 둔다.
String chosungOf(String text) => String.fromCharCodes(
  text.runes.expand((r) {
    if (r < 0xAC00 || r > 0xD7A3) return [r];
    return _cho[(r - 0xAC00) ~/ 28 ~/ 21].runes;
  }),
);

const _jung = [
  'ㅏ',
  'ㅐ',
  'ㅑ',
  'ㅒ',
  'ㅓ',
  'ㅔ',
  'ㅕ',
  'ㅖ',
  'ㅗ',
  'ㅘ',
  'ㅙ',
  'ㅚ',
  'ㅛ',
  'ㅜ',
  'ㅝ',
  'ㅞ',
  'ㅟ',
  'ㅠ',
  'ㅡ',
  'ㅢ',
  'ㅣ',
];
const _jong = [
  '',
  'ㄱ',
  'ㄲ',
  'ㄳ',
  'ㄴ',
  'ㄵ',
  'ㄶ',
  'ㄷ',
  'ㄹ',
  'ㄺ',
  'ㄻ',
  'ㄼ',
  'ㄽ',
  'ㄾ',
  'ㄿ',
  'ㅀ',
  'ㅁ',
  'ㅂ',
  'ㅄ',
  'ㅅ',
  'ㅆ',
  'ㅇ',
  'ㅈ',
  'ㅊ',
  'ㅋ',
  'ㅌ',
  'ㅍ',
  'ㅎ',
];

/// 한글을 자모로 푼다. 벤 → ㅂㅔㄴ. 한글이 아니면 그대로 둔다.
///
/// **왜 자모로 재는가.** 오타를 음절 단위로 세면 '밴치프레스'는 다섯 자 중
/// 한 자가 틀린 것(20%)이지만, 실제로 틀린 건 ㅔ/ㅐ 하나다 — 자모로는 열한
/// 개 중 하나(9%)다. 음절로 세면 한글에만 유독 가혹해서, 오타를 봐주려고
/// 한도를 올리면 이번엔 영어에서 엉뚱한 것이 걸린다. 자모로 재면 언어마다
/// 다른 한도를 둘 이유가 없어진다.
String jamoOf(String text) {
  final out = StringBuffer();
  for (final r in text.runes) {
    if (r < 0xAC00 || r > 0xD7A3) {
      out.writeCharCode(r);
      continue;
    }
    final code = r - 0xAC00;
    out.write(_cho[code ~/ 588]);
    out.write(_jung[(code % 588) ~/ 28]);
    out.write(_jong[code % 28]);
  }
  return out.toString();
}

/// ko, en, ja, 简体, 繁體, es, vi, th, [별칭]
const exercises = <Exercise>[
  // 가슴
  Exercise(
    '벤치프레스',
    'Bench Press',
    'ベンチプレス',
    '卧推',
    '臥推',
    'Press de Banca',
    'Đẩy Ngực',
    'เบนช์เพรส',
    'bp',
  ),
  Exercise(
    '인클라인 벤치프레스',
    'Incline Bench Press',
    'インクラインベンチプレス',
    '上斜卧推',
    '上斜臥推',
    'Press Inclinado',
    'Đẩy Ngực Dốc Lên',
    'เบนช์เพรสเอียงขึ้น',
  ),
  Exercise(
    '디클라인 벤치프레스',
    'Decline Bench Press',
    'デクラインベンチプレス',
    '下斜卧推',
    '下斜臥推',
    'Press Declinado',
    'Đẩy Ngực Dốc Xuống',
    'เบนช์เพรสเอียงลง',
  ),
  Exercise(
    '덤벨 프레스',
    'Dumbbell Press',
    'ダンベルプレス',
    '哑铃卧推',
    '啞鈴臥推',
    'Press con Mancuernas',
    'Đẩy Tạ Đơn',
    'ดัมเบลเพรส',
    'db press',
  ),
  Exercise(
    '인클라인 덤벨 프레스',
    'Incline Dumbbell Press',
    'インクラインダンベルプレス',
    '上斜哑铃卧推',
    '上斜啞鈴臥推',
    'Press Inclinado con Mancuernas',
    'Đẩy Tạ Đơn Dốc Lên',
    'ดัมเบลเพรสเอียงขึ้น',
  ),
  Exercise(
    '체스트 프레스',
    'Chest Press',
    'チェストプレス',
    '坐姿推胸',
    '坐姿推胸',
    'Press de Pecho',
    'Đẩy Ngực Máy',
    'เชสต์เพรส',
    '',
    [
      '인시그니아 체스트 프레스',
      '듀얼 액시스 체스트 프레스',
      'Life Fitness Insignia Chest Press',
      'Life Fitness Insignia Dual Axis Chest Press',
      'DRAX Pure Plate Chest Press',
      'DRAX Chest Weight TWMA-403',
    ],
  ),
  Exercise(
    '펙덱 플라이',
    'Pec Deck Fly',
    'ペックデックフライ',
    '蝴蝶机夹胸',
    '蝴蝶機夾胸',
    'Contractora',
    'Ép Ngực Máy',
    'เพคเด็คฟลาย',
    '',
    [
      '버터플라이',
      '머신 플라이',
      '해머 슈퍼 플라이',
      'Hammer Strength Plate Loaded Super Fly',
      'DRAX Pure Plate Pec Deck Fly',
      'DRAX Pure Plate Pectoral Fly',
      'DRAX Butterfly TWMA-306',
    ],
  ),
  Exercise(
    '케이블 크로스오버',
    'Cable Crossover',
    'ケーブルクロスオーバー',
    '绳索夹胸',
    '繩索夾胸',
    'Cruce de Poleas',
    'Kéo Cáp Chéo',
    'เคเบิลครอสโอเวอร์',
    '',
    ['DRAX Cable Crossover TWMA-401'],
  ),
  Exercise(
    '푸시업',
    'Push Up',
    'プッシュアップ',
    '俯卧撑',
    '伏地挺身',
    'Flexiones',
    'Hít Đất',
    'วิดพื้น',
    'pushup',
  ),
  // 등
  Exercise(
    '데드리프트',
    'Deadlift',
    'デッドリフト',
    '硬拉',
    '硬舉',
    'Peso Muerto',
    'Nâng Tạ Đất',
    'เดดลิฟต์',
    'dl dead lift',
  ),
  Exercise(
    '루마니안 데드리프트',
    'Romanian Deadlift',
    'ルーマニアンデッドリフト',
    '罗马尼亚硬拉',
    '羅馬尼亞硬舉',
    'Peso Muerto Rumano',
    'Nâng Tạ Kiểu Romania',
    'โรมาเนียนเดดลิฟต์',
    'rdl',
  ),
  Exercise(
    '랫풀다운',
    'Lat Pulldown',
    'ラットプルダウン',
    '高位下拉',
    '滑輪下拉',
    'Jalón al Pecho',
    'Kéo Xô',
    'แลทพูลดาวน์',
    'pull down',
  ),
  Exercise(
    '풀업',
    'Pull Up',
    'プルアップ',
    '引体向上',
    '引體向上',
    'Dominadas',
    'Hít Xà',
    'พูลอัพ',
    '턱걸이 pullup',
  ),
  Exercise(
    '친업',
    'Chin Up',
    'チンニング',
    '反握引体向上',
    '反握引體向上',
    'Dominadas Supinas',
    'Hít Xà Ngửa',
    'ชินอัพ',
    'chinup',
  ),
  Exercise(
    '바벨로우',
    'Barbell Row',
    'ベントオーバーロー',
    '杠铃划船',
    '槓鈴划船',
    'Remo con Barra',
    'Chèo Tạ Đòn',
    'บาร์เบลโรว์',
  ),
  Exercise(
    '덤벨로우',
    'Dumbbell Row',
    'ワンハンドローイング',
    '哑铃划船',
    '啞鈴划船',
    'Remo con Mancuerna',
    'Chèo Tạ Đơn',
    'ดัมเบลโรว์',
    'db row',
  ),
  Exercise(
    '시티드 로우',
    'Seated Row',
    'シーテッドロー',
    '坐姿划船',
    '坐姿划船',
    'Remo Sentado',
    'Chèo Ngồi',
    'ซีทเต็ดโรว์',
    '',
    ['Life Fitness Insignia Row', 'DRAX Seated Row TWMA-311'],
  ),
  Exercise(
    '케이블 로우',
    'Cable Row',
    'ケーブルロー',
    '绳索划船',
    '繩索划船',
    'Remo en Polea',
    'Chèo Cáp',
    'เคเบิลโรว์',
  ),
  Exercise(
    '티바로우',
    'T-Bar Row',
    'Tバーロー',
    'T杠划船',
    'T槓划船',
    'Remo en T',
    'Chèo T-Bar',
    'ทีบาร์โรว์',
    'tbar',
    [
      '해머 티바로우',
      '아이소 래터럴 티바로우',
      'Hammer Strength Iso-Lateral T-Bar Row',
      'Hammer Strength T-Bar Row',
      'DRAX Pure Plate T-Bar Row',
    ],
  ),
  // 하체
  Exercise(
    '스쿼트',
    'Squat',
    'スクワット',
    '深蹲',
    '深蹲',
    'Sentadilla',
    'Squat',
    'สควอท',
    // 백스쿼트·바벨 스쿼트는 스쿼트다. 이름 열쇠는 오타 거리로 잇지 않으니
    // (핵스쿼트와 자모 하나 차이) 별칭으로 둔다.
    '스쾃 백스쿼트 바벨스쿼트 backsquat barbellsquat',
  ),
  Exercise(
    '프론트 스쿼트',
    'Front Squat',
    'フロントスクワット',
    '前蹲',
    '前蹲',
    'Sentadilla Frontal',
    'Squat Trước',
    'ฟรอนต์สควอท',
  ),
  Exercise(
    '핵스쿼트',
    'Hack Squat',
    'ハックスクワット',
    '哈克深蹲',
    '哈克深蹲',
    'Hack Squat',
    'Hack Squat',
    'แฮ็คสควอท',
    '',
    [
      '핵 프레스',
      '슈퍼 핵스쿼트',
      '해머 핵스쿼트',
      'Hammer Strength Plate Loaded Hack Squat',
      'Panatta Super Hack Squat',
      'Panatta Hack Squat',
      'DRAX Pure Plate Hack Squat',
      'DRAX Pure Plate Hack Press',
    ],
  ),
  Exercise(
    '레그프레스',
    'Leg Press',
    'レッグプレス',
    '腿举',
    '腿推',
    'Prensa de Piernas',
    'Đạp Đùi',
    'เลกเพรส',
  ),
  Exercise(
    '레그익스텐션',
    'Leg Extension',
    'レッグエクステンション',
    '腿屈伸',
    '腿伸展',
    'Extensión de Piernas',
    'Duỗi Chân',
    'เลกเอ็กซ์เทนชัน',
    '',
    [
      '해머 레그익스텐션',
      '아이소 래터럴 레그 익스텐션',
      'Hammer Strength Iso-Lateral Leg Extension',
      'Hammer Strength Plate Loaded Leg Extension',
      'Life Fitness Insignia Leg Extension',
      'DRAX Leg Extension TWMA-102',
    ],
  ),
  Exercise(
    '레그컬',
    'Leg Curl',
    'レッグカール',
    '腿弯举',
    '腿彎舉',
    'Curl Femoral',
    'Cuốn Chân',
    'เลกเคิร์ล',
  ),
  Exercise(
    '런지',
    'Lunge',
    'ランジ',
    '弓步蹲',
    '弓步蹲',
    'Zancadas',
    'Chùng Chân',
    'ลันจ์',
  ),
  Exercise(
    '불가리안 스플릿 스쿼트',
    'Bulgarian Split Squat',
    'ブルガリアンスクワット',
    '保加利亚分腿蹲',
    '保加利亞分腿蹲',
    'Sentadilla Búlgara',
    'Squat Bulgaria',
    'บัลแกเรียนสปลิทสควอท',
  ),
  Exercise(
    '힙쓰러스트',
    'Hip Thrust',
    'ヒップスラスト',
    '臀推',
    '臀推',
    'Empuje de Cadera',
    'Đẩy Hông',
    'ฮิปทรัสต์',
  ),
  Exercise(
    '카프레이즈',
    'Calf Raise',
    'カーフレイズ',
    '提踵',
    '提踵',
    'Elevación de Talones',
    'Nhón Bắp Chân',
    'คาล์ฟเรส',
  ),
  Exercise(
    '레그레이즈',
    'Leg Raise',
    'レッグレイズ',
    '举腿',
    '舉腿',
    'Elevación de Piernas',
    'Nâng Chân',
    'เลกเรส',
  ),
  // 어깨
  Exercise(
    '오버헤드프레스',
    'Overhead Press',
    'オーバーヘッドプレス',
    '站姿推举',
    '站姿推舉',
    'Press Militar',
    'Đẩy Vai Qua Đầu',
    'โอเวอร์เฮดเพรส',
    'ohp',
  ),
  Exercise(
    '숄더프레스',
    'Shoulder Press',
    'ショルダープレス',
    '肩推',
    '肩推',
    'Press de Hombro',
    'Đẩy Vai',
    'โชลเดอร์เพรส',
    '',
    [
      '해머 숄더프레스',
      '해머스트렝스 아이소 래터럴 숄더 프레스',
      'Hammer Strength Iso-Lateral Shoulder Press',
      'Hammer Strength Plate Loaded Shoulder Press',
      'Life Fitness Insignia Shoulder Press',
      'DRAX Pure Plate Shoulder Press',
    ],
  ),
  Exercise(
    '덤벨 숄더프레스',
    'Dumbbell Shoulder Press',
    'ダンベルショルダープレス',
    '哑铃肩推',
    '啞鈴肩推',
    'Press de Hombro con Mancuernas',
    'Đẩy Vai Tạ Đơn',
    'ดัมเบลโชลเดอร์เพรส',
  ),
  Exercise(
    '사이드 레터럴 레이즈',
    'Lateral Raise',
    'サイドレイズ',
    '侧平举',
    '側平舉',
    'Elevación Lateral',
    'Nâng Tạ Ngang Vai',
    'ไซด์เรส',
    'side lateral',
  ),
  Exercise(
    '프론트 레이즈',
    'Front Raise',
    'フロントレイズ',
    '前平举',
    '前平舉',
    'Elevación Frontal',
    'Nâng Tạ Trước',
    'ฟรอนต์เรส',
  ),
  Exercise(
    '벤트오버 레터럴 레이즈',
    'Bent Over Lateral Raise',
    'リアレイズ',
    '俯身侧平举',
    '俯身側平舉',
    'Elevación Posterior',
    'Nâng Tạ Ngang Cúi Người',
    'เบนท์โอเวอร์เรส',
    'rear delt',
  ),
  Exercise(
    '업라이트 로우',
    'Upright Row',
    'アップライトロー',
    '直立划船',
    '直立划船',
    'Remo al Mentón',
    'Chèo Đứng',
    'อัพไรท์โรว์',
  ),
  Exercise(
    '슈러그',
    'Shrug',
    'シュラッグ',
    '耸肩',
    '聳肩',
    'Encogimientos',
    'Nhún Vai',
    'ชรัก',
    '',
    ['머신 슈러그', '시티드 슈러그', '해머 슈러그', 'Hammer Strength Seated / Standing Shrug'],
  ),
  // 팔
  Exercise(
    '바벨컬',
    'Barbell Curl',
    'バーベルカール',
    '杠铃弯举',
    '槓鈴彎舉',
    'Curl con Barra',
    'Cuốn Tạ Đòn',
    'บาร์เบลเคิร์ล',
  ),
  Exercise(
    '덤벨컬',
    'Dumbbell Curl',
    'ダンベルカール',
    '哑铃弯举',
    '啞鈴彎舉',
    'Curl con Mancuernas',
    'Cuốn Tạ Đơn',
    'ดัมเบลเคิร์ล',
    'db curl',
  ),
  Exercise(
    '해머컬',
    'Hammer Curl',
    'ハンマーカール',
    '锤式弯举',
    '錘式彎舉',
    'Curl Martillo',
    'Cuốn Tạ Búa',
    'แฮมเมอร์เคิร์ล',
  ),
  Exercise(
    '프리처컬',
    'Preacher Curl',
    'プリーチャーカール',
    '牧师凳弯举',
    '牧師椅彎舉',
    'Curl Predicador',
    'Cuốn Tạ Ghế Dốc',
    'พรีชเชอร์เคิร์ล',
  ),
  Exercise(
    '케이블컬',
    'Cable Curl',
    'ケーブルカール',
    '绳索弯举',
    '繩索彎舉',
    'Curl en Polea',
    'Cuốn Tạ Cáp',
    'เคเบิลเคิร์ล',
  ),
  Exercise(
    '트라이셉스 익스텐션',
    'Triceps Extension',
    'トライセプスエクステンション',
    '三头肌伸展',
    '三頭肌伸展',
    'Extensión de Tríceps',
    'Duỗi Tay Sau',
    'ไตรเซปส์เอ็กซ์เทนชัน',
    'tricep',
  ),
  Exercise(
    '케이블 푸시다운',
    'Cable Pushdown',
    'プレスダウン',
    '绳索下压',
    '繩索下壓',
    'Extensión en Polea',
    'Đẩy Cáp Xuống',
    'เคเบิลพุชดาวน์',
    'push down',
  ),
  Exercise(
    '딥스',
    'Dips',
    'ディップス',
    '双杠臂屈伸',
    '雙槓臂屈伸',
    'Fondos',
    'Hít Xà Kép',
    'ดิพส์',
    'dip',
  ),
  Exercise(
    '킥백',
    'Kickback',
    'キックバック',
    '臂屈伸后踢',
    '臂屈伸後踢',
    'Patada de Tríceps',
    'Đá Tay Sau',
    'คิกแบ็ก',
    'kick back',
  ),
  // 코어·유산소
  Exercise('플랭크', 'Plank', 'プランク', '平板支撑', '棒式', 'Plancha', 'Plank', 'แพลงก์'),
  Exercise(
    '사이드 플랭크',
    'Side Plank',
    'サイドプランク',
    '侧平板支撑',
    '側棒式',
    'Plancha Lateral',
    'Plank Nghiêng',
    'ไซด์แพลงก์',
  ),
  Exercise(
    '크런치',
    'Crunch',
    'クランチ',
    '卷腹',
    '捲腹',
    'Abdominales',
    'Gập Bụng',
    'ครันช์',
  ),
  Exercise(
    '싯업',
    'Sit Up',
    'シットアップ',
    '仰卧起坐',
    '仰臥起坐',
    'Abdominales Completos',
    'Gập Bụng Toàn Phần',
    'ซิทอัพ',
    'situp',
  ),
  Exercise(
    '행잉 레그레이즈',
    'Hanging Leg Raise',
    'ハンギングレッグレイズ',
    '悬垂举腿',
    '懸垂舉腿',
    'Elevación de Piernas Colgado',
    'Nâng Chân Treo Xà',
    'แฮงกิงเลกเรส',
  ),
  Exercise(
    '러시안 트위스트',
    'Russian Twist',
    'ロシアンツイスト',
    '俄罗斯转体',
    '俄羅斯轉體',
    'Giro Ruso',
    'Xoay Người Nga',
    'รัสเซียนทวิสต์',
  ),
  Exercise(
    '러닝',
    'Running',
    'ランニング',
    '跑步',
    '跑步',
    'Correr',
    'Chạy Bộ',
    'วิ่ง',
    'run treadmill',
  ),
  Exercise(
    '사이클',
    'Cycling',
    'サイクリング',
    '骑行',
    '騎行',
    'Bicicleta',
    'Đạp Xe',
    'ปั่นจักรยาน',
    'bike',
  ),
  Exercise(
    '로잉',
    'Rowing',
    'ローイング',
    '划船机',
    '划船機',
    'Remo',
    'Chèo Thuyền',
    'โรว์อิ้ง',
  ),
  Exercise(
    '버피',
    'Burpee',
    'バーピー',
    '波比跳',
    '波比跳',
    'Burpees',
    'Burpee',
    'เบอร์ปี้',
  ),
  Exercise(
    '점핑잭',
    'Jumping Jack',
    'ジャンピングジャック',
    '开合跳',
    '開合跳',
    'Saltos de Tijera',
    'Nhảy Dang Tay Chân',
    'จัมปิ้งแจ็ค',
  ),
  // 음식 표에 같은 이름의 제품이 있는 운동(2026-09-23 운영 표 실측: 굿모닝·클린).
  // 사전에 있어야 입력 줄이 끼니로 가르지 않는다. '클린' 만 친 줄은 사전 별칭이 아니라
  // 운동 낱말(parser.dart _exerciseWords)로 잡는다 — 별칭이면 기록 검색이 '클린' 을
  // 파워클린으로 바꾼다.
  Exercise(
    '굿모닝',
    'Good Morning',
    'グッドモーニング',
    '早安式体前屈',
    '早安式體前屈',
    'Buenos Días',
    'Good Morning',
    'กู๊ดมอร์นิ่ง',
  ),
  Exercise(
    '파워클린',
    'Power Clean',
    'パワークリーン',
    '高翻',
    '高翻',
    'Cargada de Potencia',
    'Power Clean',
    'พาวเวอร์คลีน',
  ),
  // 헬스장 머신(2026-09-26 조사: Hammer Strength · Life Fitness · Technogym · Cybex · DRAX 등
  // 카탈로그). 브랜드 제품명은 별칭(more)으로 — 운동은 기구 종류로 묶는다.
  Exercise(
    '아이소 래터럴 체스트 프레스',
    'Iso-Lateral Chest Press',
    'アイソラテラル・チェストプレス',
    '单侧独立推胸机',
    '單側獨立推胸機',
    'Press de pecho iso-lateral',
    'Đẩy ngực máy Iso-Lateral',
    'ไอโซแลเทอรัล เชสต์เพรส',
    '',
    [
      '해머 체스트 프레스',
      '해머스트렝스 아이소 래터럴 벤치 프레스',
      '해머 호리즌탈 벤치',
      'Hammer Strength Iso-Lateral Bench Press',
      'Hammer Strength Iso-Lateral Horizontal Bench Press',
      'DRAX Pure Plate Super Horizontal Bench Press',
      'DRAX Pure Plate Leverage Chest Press',
      '디랙스 퓨어플레이트 체스트 프레스',
    ],
  ),
  Exercise(
    '인클라인 체스트 프레스 머신',
    'Incline Chest Press Machine',
    'インクライン・チェストプレスマシン',
    '上斜推胸机',
    '上斜推胸機',
    'Press inclinado en máquina',
    'Đẩy ngực dốc lên bằng máy',
    'อินไคลน์ เชสต์เพรส แมชชีน',
    '',
    [
      '머신 인클라인 프레스',
      '해머 인클라인 프레스',
      '해머스트렝스 아이소 래터럴 인클라인 프레스',
      'Hammer Strength Iso-Lateral Incline Press',
      'Hammer Strength Plate Loaded Incline Press',
      'DRAX Pure Plate Incline Chest Press',
      '디랙스 인클라인 체스트 프레스',
    ],
  ),
  Exercise(
    '디클라인 체스트 프레스 머신',
    'Decline Chest Press Machine',
    'デクライン・チェストプレスマシン',
    '下斜推胸机',
    '下斜推胸機',
    'Press declinado en máquina',
    'Đẩy ngực dốc xuống bằng máy',
    'ดีไคลน์ เชสต์เพรส แมชชีน',
    '',
    [
      '머신 디클라인 프레스',
      '해머 디클라인 프레스',
      '해머스트렝스 아이소 래터럴 디클라인 체스트 프레스',
      'Hammer Strength Iso-Lateral Decline Chest Press',
      'Hammer Strength Plate Loaded Decline Chest Press',
    ],
  ),
  Exercise(
    '와이드 체스트 프레스',
    'Iso-Lateral Wide Chest Press',
    'ワイドチェストプレス',
    '宽距推胸机',
    '寬距推胸機',
    'Press de pecho amplio',
    'Đẩy ngực tay rộng bằng máy',
    'ไวด์ เชสต์เพรส',
    '',
    [
      '와이드 체스트',
      '해머 와이드 체스트',
      '해머스트렝스 아이소 래터럴 와이드 체스트',
      'Hammer Strength Iso-Lateral Wide Chest',
    ],
  ),
  Exercise(
    '슈퍼 인클라인 프레스',
    'Iso-Lateral Super Incline Press',
    'スーパーインクラインプレス',
    '大角度上斜推举机',
    '大角度上斜推舉機',
    'Press súper inclinado',
    'Đẩy ngực siêu dốc bằng máy',
    'ซูเปอร์ อินไคลน์ เพรส',
    '',
    [
      '해머 슈퍼 인클라인',
      '해머스트렝스 아이소 래터럴 슈퍼 인클라인 프레스',
      'Hammer Strength Iso-Lateral Super Incline Press',
    ],
  ),
  Exercise(
    '스미스머신 벤치프레스',
    'Smith Machine Bench Press',
    'スミスマシン・ベンチプレス',
    '史密斯卧推',
    '史密斯臥推',
    'Press de banca en máquina Smith',
    'Đẩy ngực máy Smith',
    'สมิธแมชชีน เบนช์เพรส',
    '',
    [
      '스미스 벤치',
      '스미스 벤치프레스',
      'Smith Bench Press',
      'Hammer Strength Smith Machine',
      'DRAX Smith Machine TWMA-701',
    ],
  ),
  Exercise(
    '스미스머신 인클라인 벤치프레스',
    'Smith Machine Incline Bench Press',
    'スミスマシン・インクラインベンチプレス',
    '史密斯上斜卧推',
    '史密斯上斜臥推',
    'Press inclinado en máquina Smith',
    'Đẩy ngực dốc lên máy Smith',
    'สมิธแมชชีน อินไคลน์ เบนช์เพรส',
    '',
    ['스미스 인클라인', '스미스 인클라인 벤치', 'Smith Incline Press'],
  ),
  Exercise(
    '시티드 딥스 머신',
    'Seated Dip Machine',
    'シーテッドディップマシン',
    '坐姿臂屈伸机',
    '坐姿臂屈伸機',
    'Fondos sentado en máquina',
    'Máy dips ngồi',
    'ซีทเต็ด ดิป แมชชีน',
    '',
    [
      '머신 딥스',
      '딥스 머신',
      '시티드 딥',
      '트라이셉스 프레스',
      '해머 시티드 딥',
      'Hammer Strength Plate Loaded Seated Dip',
      'Life Fitness Insignia Triceps Press',
    ],
  ),
  Exercise(
    '어시스트 딥스',
    'Assisted Dip',
    'アシステッドディップ',
    '辅助臂屈伸',
    '輔助臂屈伸',
    'Fondos asistidos',
    'Dips có hỗ trợ',
    'แอสซิสเต็ด ดิป',
    '',
    ['어시스티드 딥스', '딥스 어시스트 머신', 'Cybex Eagle NX Assisted Dip/Pull-up'],
  ),
  Exercise(
    '어시스트 풀업',
    'Assisted Pull-up',
    'アシステッドプルアップ',
    '辅助引体向上',
    '輔助引體向上',
    'Dominadas asistidas',
    'Kéo xà có hỗ trợ',
    'แอสซิสเต็ด พูลอัพ',
    '',
    ['어시스티드 풀업', '어시스트 친업', '풀업 어시스트 머신'],
  ),
  Exercise(
    '하이 로우',
    'High Row Machine',
    'ハイロー',
    '高位划船机',
    '高位划船機',
    'Remo alto en máquina',
    'Máy kéo cao (High Row)',
    'ไฮโรว์แมชชีน',
    '',
    [
      '해머 하이로우',
      '해머스트렝스 아이소 래터럴 하이 로우',
      '머신 하이로우',
      'Hammer Strength Iso-Lateral High Row',
      'Hammer Strength Plate Loaded High Row',
      'DRAX Pure Plate High Row',
      '디랙스 하이로우',
    ],
  ),
  Exercise(
    '머신 로우로우',
    'Low Row Machine',
    'ローロー',
    '低位划船机',
    '低位划船機',
    'Remo bajo en máquina',
    'Máy kéo thấp (Low Row)',
    'โลว์โรว์แมชชีน',
    '',
    [
      '해머 로우로우',
      '해머스트렝스 아이소 래터럴 로우 로우',
      '머신 로우로우',
      'Hammer Strength Iso-Lateral Low Row',
      'DRAX Pure Plate Low Row',
      'Technogym Selection 900 Low Row',
    ],
  ),
  Exercise(
    '아이소 래터럴 로우',
    'Iso-Lateral Row',
    'アイソラテラルロー',
    '单侧独立划船机',
    '單側獨立划船機',
    'Remo iso-lateral',
    'Máy kéo Iso-Lateral',
    'ไอโซแลทเทอรัลโรว์',
    '',
    [
      '해머 로우',
      '해머스트렝스 아이소 래터럴 로우',
      '머신 로우',
      '프론트 로우',
      'Hammer Strength Iso-Lateral Row',
      'Hammer Strength Plate Loaded Row',
      'DRAX Pure Plate ISO Linear Row',
      'DRAX Pure Plate Front Row',
      'DRAX Pure Plate Extreme Row',
    ],
  ),
  Exercise(
    'DY 로우',
    'Iso-Lateral D.Y. Row',
    'D.Y.ロー',
    'D.Y.划船机',
    'D.Y.划船機',
    'Remo D.Y.',
    'Máy kéo D.Y.',
    'ดีวายโรว์',
    '',
    [
      '디와이 로우',
      '도리안 예이츠 로우',
      '해머 DY 로우',
      'Hammer Strength Iso-Lateral D.Y. Row',
    ],
  ),
  Exercise(
    '머신 랫풀다운',
    'Machine Lat Pulldown',
    'マシンラットプルダウン',
    '器械高位下拉',
    '器械高位下拉',
    'Jalón al pecho en máquina',
    'Máy kéo xô (Lat Pulldown)',
    'แมชชีนแลตพูลดาวน์',
    '',
    [
      '해머 랫풀다운',
      '해머스트렝스 아이소 래터럴 프론트 랫 풀다운',
      '머신 풀다운',
      '듀얼 액시스 풀다운',
      '로터리 풀다운',
      'Hammer Strength Iso-Lateral Front Lat Pulldown',
      'Hammer Strength Plate Loaded Pulldown',
      'Life Fitness Insignia Pulldown',
      'Life Fitness Insignia Dual Axis Pulldown',
      'Technogym Selection 900 Lat Machine',
      'DRAX Pure Plate Rotary Pulldown',
    ],
  ),
  Exercise(
    '와이드 풀다운',
    'Iso-Lateral Wide Pulldown',
    'ワイドプルダウン',
    '宽握下拉机',
    '寬握下拉機',
    'Jalón agarre ancho en máquina',
    'Máy kéo xô tay rộng',
    'ไวด์พูลดาวน์',
    '',
    [
      '해머 와이드 풀다운',
      '해머스트렝스 아이소 래터럴 와이드 풀다운',
      'Hammer Strength Iso-Lateral Wide Pulldown',
    ],
  ),
  Exercise(
    '풀오버 머신',
    'Pullover Machine',
    'プルオーバーマシン',
    '器械直臂拉',
    '器械直臂拉',
    'Máquina de pullover',
    'Máy Pullover',
    'พูลโอเวอร์แมชชีน',
    '',
    ['머신 풀오버', '해머 풀오버', 'Hammer Strength Plate Loaded Pullover'],
  ),
  Exercise(
    '백 익스텐션 머신',
    'Back Extension Machine',
    'バックエクステンションマシン',
    '器械背部伸展',
    '器械背部伸展',
    'Máquina de extensión lumbar',
    'Máy duỗi lưng',
    'แบ็คเอ็กซ์เทนชันแมชชีน',
    '',
    [
      '머신 백익스텐션',
      '로워 백',
      'Life Fitness Insignia Back Extension',
      'Technogym Selection 900 Lower Back',
      'DRAX Back Extension TWMA-202',
    ],
  ),
  Exercise(
    '리버스 하이퍼',
    'Reverse Hyperextension',
    'リバースハイパーエクステンション',
    '反向山羊挺身',
    '反向山羊挺身',
    'Hiperextensión inversa',
    'Reverse Hyper (duỗi hông ngược)',
    'รีเวิร์สไฮเปอร์',
    '',
    [
      '리버스 하이퍼익스텐션',
      '해머 글루트햄 리버스 하이퍼',
      'Hammer Strength Glute Ham / Reverse Hyper',
    ],
  ),
  Exercise(
    '글루트 햄 레이즈',
    'Glute Ham Raise',
    'グルートハムレイズ',
    '臀腿抬升',
    '臀腿抬升',
    'Elevación glúteo-isquiotibial (GHR)',
    'Glute Ham Raise',
    'กลูทแฮมเรส',
    '',
    ['GHR', '글루트햄'],
  ),
  Exercise(
    '노르딕 햄 컬',
    'Assisted Nordic Hamstring Curl',
    'アシスト・ノルディックハムカール',
    '辅助北欧腘绳肌弯举',
    '輔助北歐腿後彎舉',
    'Curl nórdico asistido en máquina',
    'Nordic ham curl hỗ trợ bằng máy',
    'นอร์ดิกแฮมเคิร์ลแบบเครื่องช่วย',
    '',
    ['노르딕 컬', '어시스트 노르딕', 'Hammer Strength Plate Loaded Assisted Nordic Ham'],
  ),
  Exercise(
    '머신 레터럴 레이즈',
    'Lateral Raise Machine',
    'マシン・ラテラルレイズ',
    '器械侧平举',
    '器械側平舉',
    'Elevación lateral en máquina',
    'Nâng tạ ngang bằng máy',
    'แมชชีนเลทเทอรัลเรส',
    '',
    [
      '레터럴 레이즈 머신',
      '사레레 머신',
      '해머 레터럴 레이즈',
      '델트 머신',
      'Hammer Strength Plate Loaded Lateral Raise',
      'Life Fitness Insignia Lateral Raise',
      'Technogym Selection 900 Delts Machine',
      'DRAX Pure Plate Lateral Raise',
    ],
  ),
  Exercise(
    '바이킹 프레스',
    'Viking Press',
    'バイキングプレス',
    '维京推举',
    '維京推舉',
    'Press vikingo',
    'Viking press',
    'ไวกิ้งเพรส',
    '',
    ['바이킹 숄더 프레스', 'DRAX Pure Plate Viking Press', '디랙스 바이킹 프레스'],
  ),
  Exercise(
    '스미스머신 숄더프레스',
    'Smith Machine Shoulder Press',
    'スミスマシン・ショルダープレス',
    '史密斯机肩推',
    '史密斯機肩推',
    'Press de hombros en máquina Smith',
    'Đẩy vai máy Smith',
    'สมิทแมชชีนชอลเดอร์เพรส',
    '',
    ['스미스 숄더프레스', '스미스 오버헤드 프레스', 'DRAX Pure Plate Dual Power Smith Shoulder'],
  ),
  Exercise(
    '머신 바이셉스 컬',
    'Biceps Curl Machine',
    'マシン・バイセップスカール',
    '器械二头弯举',
    '器械二頭彎舉',
    'Curl de bíceps en máquina',
    'Cuốn tay trước bằng máy',
    'แมชชีนไบเซ็ปเคิร์ล',
    '',
    [
      '머신 컬',
      '암컬 머신',
      '해머 시티드 바이셉스',
      'Hammer Strength Plate Loaded Seated Biceps',
      'Cybex Eagle NX Arm Curl',
    ],
  ),
  Exercise(
    '머신 트라이셉스 익스텐션',
    'Triceps Extension Machine',
    'マシン・トライセップスエクステンション',
    '器械三头臂屈伸',
    '器械三頭伸展',
    'Extensión de tríceps en máquina',
    'Duỗi tay sau bằng máy',
    'แมชชีนไตรเซ็ปเอ็กซ์เทนชัน',
    '',
    [
      '트라이셉스 익스텐션 머신',
      '암 익스텐션',
      'Life Fitness Insignia Triceps Extension',
      'Technogym Selection 900 Arm Extension',
    ],
  ),
  Exercise(
    '그립 머신',
    'Plate-Loaded Gripper',
    'グリップマシン',
    '握力器械',
    '握力器械',
    'Máquina de agarre',
    'Máy tập lực nắm',
    'เครื่องฝึกแรงบีบมือ',
    '',
    ['그리퍼', '악력 머신', 'Hammer Strength Plate Loaded Gripper'],
  ),
  Exercise(
    'V 스쿼트',
    'V-Squat Machine',
    'Vスクワット',
    'V型深蹲机',
    'V型深蹲機',
    'Sentadilla en V',
    'V-squat',
    'วีสควอท',
    '',
    ['브이 스쿼트', 'DRAX Pure Plate V-Squat', '디랙스 V스쿼트'],
  ),
  Exercise(
    '리버스 V 스쿼트',
    'Reverse V-Squat',
    'リバースVスクワット',
    '反向V型深蹲',
    '反向V型深蹲',
    'Sentadilla en V inversa',
    'Reverse V-squat',
    'รีเวิร์สวีสควอท',
    '',
    [
      '리버스 브이 스쿼트',
      '해머 리버스 V 스쿼트',
      'Hammer Strength Plate Loaded Reverse V-Squat',
    ],
  ),
  Exercise(
    '펜듈럼 스쿼트',
    'Pendulum Squat',
    'ペンデュラムスクワット',
    '钟摆深蹲',
    '鐘擺深蹲',
    'Sentadilla péndulo',
    'Pendulum squat (squat con lắc)',
    'เพนดูลัมสควอท',
    '',
    [
      '펜듈럼',
      '해머 펜듈럼 X 스쿼트',
      'Hammer Strength Plate Loaded Pendulum-X Squat',
      'Panatta Super Pendulum Squat',
      'Panatta Pendulum Squat',
      'gym80 Pure Kraft Pendulum Squat 4353N',
    ],
  ),
  Exercise(
    '벨트 스쿼트',
    'Belt Squat Machine',
    'ベルトスクワット',
    '腰带深蹲',
    '腰帶深蹲',
    'Sentadilla con cinturón',
    'Belt squat (squat đai hông)',
    'เบลท์สควอท',
    '',
    [
      '벨트스쿼트',
      '해머 벨트 스쿼트',
      'Hammer Strength Plate Loaded Belt Squat',
      'gym80 Pure Kraft Belt Squat 4360',
    ],
  ),
  Exercise(
    '스쿼트 머신',
    'Squat Press Machine',
    'スクワットマシン',
    '深蹲机',
    '深蹲機',
    'Máquina de sentadilla',
    'Máy squat',
    'เครื่องสควอท',
    '',
    [
      '슈퍼 스쿼트',
      '스쿼트 프레스',
      '해머 슈퍼 스쿼트 프레스',
      '그라운드 베이스 스쿼트',
      'Hammer Strength Plate Loaded Super Squat Press',
      'Hammer Strength Ground Base Squat / High Pull',
      'Panatta Super Squat Machine',
    ],
  ),
  Exercise(
    '스미스머신 스쿼트',
    'Smith Machine Squat',
    'スミスマシンスクワット',
    '史密斯深蹲',
    '史密斯深蹲',
    'Sentadilla en máquina Smith',
    'Squat máy Smith',
    'สมิธแมชชีนสควอท',
    '',
    [
      '스미스 스쿼트',
      '버티컬 스미스',
      'Hammer Strength Plate-Loaded Vertical Smith Machine',
    ],
  ),
  Exercise(
    '45도 레그프레스',
    '45° Leg Press',
    '45度レッグプレス',
    '45度倒蹬',
    '45度腿推',
    'Prensa de piernas 45°',
    'Đạp đùi 45 độ',
    'เลกเพรส 45 องศา',
    '',
    [
      '45도 레그 프레스',
      '리니어 레그프레스',
      '파워 레그프레스',
      'Hammer Strength Plate Loaded Linear Leg Press',
      'DRAX Pure Plate Power Leg Press',
      'DRAX Power Leg Press TWMA-501',
    ],
  ),
  Exercise(
    '시티드 레그프레스',
    'Seated',
    'シーテッドレッグプレス',
    '坐姿腿举',
    '坐姿腿推',
    'Prensa de piernas sentado',
    'Đạp đùi ngồi',
    'ซีทเต็ดเลกเพรส',
    '',
    [
      '호리즌탈 레그프레스',
      '수평 레그프레스',
      '아크 레그프레스',
      '아이소 래터럴 레그프레스',
      'Life Fitness Insignia Arc Leg Press',
      'Hammer Strength Iso-Lateral Leg Press (discontinued)',
    ],
  ),
  Exercise(
    '시티드 레그컬',
    'Seated Leg Curl',
    'シーテッドレッグカール',
    '坐姿腿弯举',
    '坐姿腿彎舉',
    'Curl femoral sentado',
    'Cuốn đùi sau ngồi',
    'ซีทเต็ดเลกเคิร์ล',
    '',
    [
      '앉아서 레그컬',
      'Life Fitness Insignia Seated Leg Curl',
      'DRAX Seated Leg Curl TWMA-103',
    ],
  ),
  Exercise(
    '라잉 레그컬',
    'Lying Leg Curl',
    'ライイングレッグカール',
    '俯卧腿弯举',
    '俯臥腿彎舉',
    'Curl femoral tumbado',
    'Cuốn đùi sau nằm sấp',
    'ไลอิ้งเลกเคิร์ล',
    '',
    [
      '엎드려 레그컬',
      '해머 아이소 래터럴 레그컬',
      'Hammer Strength Iso-Lateral Leg Curl',
      'Life Fitness Insignia Leg Curl',
    ],
  ),
  Exercise(
    '닐링 레그컬',
    'Kneeling Leg Curl',
    'ニーリングレッグカール',
    '跪姿腿弯举',
    '跪姿腿彎舉',
    'Curl femoral de rodillas',
    'Cuốn đùi sau quỳ gối',
    'นีลลิ่งเลกเคิร์ล',
    '',
    [
      '무릎 꿇고 레그컬',
      '해머 닐링 레그컬',
      'Hammer Strength Iso-Lateral Kneeling Leg Curl',
      'Hammer Strength Plate Loaded Kneeling Leg Curl',
      'DRAX Pure Plate Kneeling Leg Curl',
    ],
  ),
  Exercise(
    '스탠딩 레그컬',
    'Standing Leg Curl',
    'スタンディングレッグカール',
    '站姿腿弯举',
    '站姿腿彎舉',
    'Curl femoral de pie',
    'Cuốn đùi sau đứng',
    'สแตนดิ้งเลกเคิร์ล',
    '',
    ['서서 레그컬', 'gym80 Pure Kraft Standing Leg Curl'],
  ),
  Exercise(
    '힙 쓰러스트 머신',
    'Hip Thrust Machine',
    'ヒップスラストマシン',
    '臀推机',
    '臀推機',
    'Máquina de hip thrust',
    'Máy hip thrust',
    'เครื่องฮิปทรัสต์',
    '',
    [
      '머신 힙쓰러스트',
      '글루트 드라이브',
      '글루트 브릿지 머신',
      '글루트 트레이너',
      'Hammer Strength Plate Loaded Glute Drive',
      'Matrix Magnum Glute Trainer MG-PL78',
      'gym80 Pure Kraft Hip Thrust',
      'DRAX Pure Plate Hip Thrust',
      'DRAX Pure Plate Standing Hip Thrust',
      'Life Fitness Insignia Glute Bridge',
    ],
  ),
  Exercise(
    '글루트 킥백 머신',
    'Glute Kickback Machine',
    'グルートキックバックマシン',
    '臀部后踢机',
    '臀部後踢機',
    'Máquina de patada de glúteo',
    'Máy đá hông sau (glute kickback)',
    'เครื่องกลูทคิกแบ็ก',
    '',
    [
      '힙 익스텐션 머신',
      '글루트 머신',
      '글루트 프레스',
      'Life Fitness Insignia Glute',
      'Technogym Selection 900 Glute Press',
      'Precor Discovery Glute',
    ],
  ),
  Exercise(
    '힙 어브덕션',
    'Seated Hip Abduction Machine',
    'ヒップアブダクション',
    '髋外展机',
    '髖外展機',
    'Máquina de abducción de cadera',
    'Máy dạng hông (abduction)',
    'เครื่องฮิปแอบดักชัน',
    '',
    [
      '어브덕터',
      '이너타이 아웃',
      '아웃타이',
      'Life Fitness Insignia Hip Abduction/Adduction',
      'Technogym Selection 900 Abductor',
      'Cybex Eagle NX Hip Abduction/Adduction',
      'DRAX Pure Plate Link Abductor',
    ],
  ),
  Exercise(
    '스탠딩 힙 어브덕션',
    'Standing Hip Abduction Machine',
    'スタンディングヒップアブダクション',
    '站姿髋外展机',
    '站姿髖外展機',
    'Abducción de cadera de pie en máquina',
    'Máy dạng hông đứng',
    'เครื่องฮิปแอบดักชันแบบยืน',
    '',
    [
      '스탠딩 어브덕터',
      'Life Fitness Insignia Sit/Stand Hip Abductor',
      'DRAX Pure Plate Standing Abductor',
      'gym80 Pure Kraft Standing Abduction',
    ],
  ),
  Exercise(
    '스탠딩 카프레이즈 머신',
    'Standing Calf Raise Machine',
    'スタンディングカーフレイズマシン',
    '站姿提踵机',
    '站姿提踵機',
    'Máquina de elevación de talones de pie',
    'Máy nhón gót đứng',
    'เครื่องสแตนดิ้งคาล์ฟเรส',
    '',
    [
      '서서 카프레이즈',
      '해머 카프레이즈',
      'Hammer Strength Plate Loaded Calf Raise',
      'Panatta Squat and Calf',
    ],
  ),
  Exercise(
    '카프 익스텐션',
    'Seated Calf Extension',
    'カーフエクステンション',
    '坐姿蹬踵机',
    '坐姿蹬踵機',
    'Extensión de gemelos en máquina',
    'Máy đạp bắp chân',
    'เครื่องคาล์ฟเอ็กซ์เทนชัน',
    '',
    ['카프 프레스', 'Life Fitness Insignia Calf Extension'],
  ),
  Exercise(
    '티비아 레이즈 머신',
    'Tibia Dorsi-Flexion Machine',
    'チビアレイズマシン',
    '胫骨前肌训练机',
    '脛骨前肌訓練機',
    'Máquina de elevación de tibial',
    'Máy nâng mũi chân (cơ chày trước)',
    'เครื่องทิเบียเรส',
    '',
    [
      '티비알리스 레이즈',
      '정강이 운동',
      '해머 티비아',
      'Hammer Strength Plate Loaded Tibia Dorsi-Flexion',
    ],
  ),
  Exercise(
    '머신 크런치',
    'Ab Crunch Machine',
    'アブクランチマシン',
    '卷腹机',
    '捲腹機',
    'Máquina de crunch abdominal',
    'Máy gập bụng',
    'เครื่องแอบครันช์',
    '',
    [
      '앱 크런치 머신',
      '복근 머신',
      '앱도미널',
      'Hammer Strength Abdominal / Oblique Crunch',
      'Life Fitness Insignia Abdominal',
      'Technogym Selection 900 Abdominal Crunch',
      'Precor Discovery Abdominal',
    ],
  ),
  Exercise(
    '로터리 토르소',
    'Rotary Torso Machine',
    'ロータリートーソ',
    '坐姿转体机',
    '坐姿轉體機',
    'Máquina de rotación de torso',
    'Máy xoay thân',
    'เครื่องบิดลำตัว',
    '',
    [
      '토르소 로테이션',
      '회전 복근 머신',
      'Technogym Selection 900 Rotary Torso',
      'Life Fitness Insignia Torso Rotation',
      'Precor Discovery Torso',
    ],
  ),
];

/// 어느 언어의 이름으로든 그 운동을 되찾는다. 사용자가 영어 화면에서 담은
/// 'Bench Press' 도, 한글 화면의 '벤치프레스' 도 같은 한 줄을 가리킨다.
final Map<String, Exercise> exerciseByName = {
  for (final e in exercises)
    for (final n in [
      e.ko,
      e.en,
      e.ja,
      e.zhHans,
      e.zhHant,
      e.es,
      e.vi,
      e.th,
      ...e.more,
    ])
      n.toLowerCase(): e,
};

List<String> seedNames(String lang) => [
  for (final e in exercises) e.name(lang),
];

/// 사전 운동의 부위(한국어 이름 → 부위). 기록 검색의 `part` 가 이 표로 푼다.
///
/// 사전 구간 주석을 따르되 두 곳을 고쳤다: 코어·유산소 구간은 core 와 cardio 로
/// 가르고, 하체 구간의 레그레이즈는 core 로 옮긴다. 데드리프트는 구간대로 등이다 —
/// 판단이라, 확인 줄이 부위마다 든 운동을 보인다.
const exercisePart = <String, String>{
  '벤치프레스': 'chest',
  '인클라인 벤치프레스': 'chest',
  '디클라인 벤치프레스': 'chest',
  '덤벨 프레스': 'chest',
  '인클라인 덤벨 프레스': 'chest',
  '체스트 프레스': 'chest',
  '펙덱 플라이': 'chest',
  '케이블 크로스오버': 'chest',
  '푸시업': 'chest',
  '데드리프트': 'back',
  '루마니안 데드리프트': 'back',
  // 힙 힌지·바닥에서 끄는 들기는 데드리프트처럼 등으로 센다.
  '굿모닝': 'back',
  '파워클린': 'back',
  '랫풀다운': 'back',
  '풀업': 'back',
  '친업': 'back',
  '바벨로우': 'back',
  '덤벨로우': 'back',
  '시티드 로우': 'back',
  '케이블 로우': 'back',
  '티바로우': 'back',
  '스쿼트': 'legs',
  '프론트 스쿼트': 'legs',
  '핵스쿼트': 'legs',
  '레그프레스': 'legs',
  '레그익스텐션': 'legs',
  '레그컬': 'legs',
  '런지': 'legs',
  '불가리안 스플릿 스쿼트': 'legs',
  '힙쓰러스트': 'legs',
  '카프레이즈': 'legs',
  '오버헤드프레스': 'shoulders',
  '숄더프레스': 'shoulders',
  '덤벨 숄더프레스': 'shoulders',
  '사이드 레터럴 레이즈': 'shoulders',
  '프론트 레이즈': 'shoulders',
  '벤트오버 레터럴 레이즈': 'shoulders',
  '업라이트 로우': 'shoulders',
  '슈러그': 'shoulders',
  '바벨컬': 'arms',
  '덤벨컬': 'arms',
  '해머컬': 'arms',
  '프리처컬': 'arms',
  '케이블컬': 'arms',
  '트라이셉스 익스텐션': 'arms',
  '케이블 푸시다운': 'arms',
  '딥스': 'arms',
  '킥백': 'arms',
  '플랭크': 'core',
  '사이드 플랭크': 'core',
  '크런치': 'core',
  '싯업': 'core',
  '행잉 레그레이즈': 'core',
  '러시안 트위스트': 'core',
  '레그레이즈': 'core',
  '러닝': 'cardio',
  '사이클': 'cardio',
  '로잉': 'cardio',
  '버피': 'cardio',
  '점핑잭': 'cardio',
  // 헬스장 머신
  '아이소 래터럴 체스트 프레스': 'chest',
  '인클라인 체스트 프레스 머신': 'chest',
  '디클라인 체스트 프레스 머신': 'chest',
  '와이드 체스트 프레스': 'chest',
  '슈퍼 인클라인 프레스': 'chest',
  '스미스머신 벤치프레스': 'chest',
  '스미스머신 인클라인 벤치프레스': 'chest',
  '시티드 딥스 머신': 'arms',
  '어시스트 딥스': 'arms',
  '어시스트 풀업': 'back',
  '하이 로우': 'back',
  '머신 로우로우': 'back',
  '아이소 래터럴 로우': 'back',
  'DY 로우': 'back',
  '머신 랫풀다운': 'back',
  '와이드 풀다운': 'back',
  '풀오버 머신': 'back',
  '백 익스텐션 머신': 'back',
  '리버스 하이퍼': 'back',
  '글루트 햄 레이즈': 'legs',
  '노르딕 햄 컬': 'legs',
  '머신 레터럴 레이즈': 'shoulders',
  '바이킹 프레스': 'shoulders',
  '스미스머신 숄더프레스': 'shoulders',
  '머신 바이셉스 컬': 'arms',
  '머신 트라이셉스 익스텐션': 'arms',
  '그립 머신': 'arms',
  'V 스쿼트': 'legs',
  '리버스 V 스쿼트': 'legs',
  '펜듈럼 스쿼트': 'legs',
  '벨트 스쿼트': 'legs',
  '스쿼트 머신': 'legs',
  '스미스머신 스쿼트': 'legs',
  '45도 레그프레스': 'legs',
  '시티드 레그프레스': 'legs',
  '시티드 레그컬': 'legs',
  '라잉 레그컬': 'legs',
  '닐링 레그컬': 'legs',
  '스탠딩 레그컬': 'legs',
  '힙 쓰러스트 머신': 'legs',
  '글루트 킥백 머신': 'legs',
  '힙 어브덕션': 'legs',
  '스탠딩 힙 어브덕션': 'legs',
  '스탠딩 카프레이즈 머신': 'legs',
  '카프 익스텐션': 'legs',
  '티비아 레이즈 머신': 'legs',
  '머신 크런치': 'core',
  '로터리 토르소': 'core',
};

/// 묶음 부위 → 든 부위. upper 는 가슴·등·어깨·팔, lower 는 하체다.
const partGroups = <String, Set<String>>{
  'upper': {'chest', 'back', 'shoulders', 'arms'},
  'lower': {'legs'},
};

/// 어느 언어의 사전 이름으로든 그 운동의 부위. 사전에 없는 이름은 null — 부위를
/// 지어내지 않는다.
String? partOf(String name) =>
    exercisePart[exerciseByName[name.trim().toLowerCase()]?.ko];

/// [part] 가 [name] 의 부위를 품는가. upper·lower 는 펼쳐서 본다.
bool inPart(String name, String part) {
  final p = partOf(name);
  return p != null && (partGroups[part]?.contains(p) ?? p == part);
}
